# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'SideDish' do
  use_modular_headers!
  pod 'Toaster', :git => 'https://github.com/devxoul/Toaster.git', :branch => 'master'
  pod 'Alamofire'
  pod 'Floaty', '~> 4.2.0'

end
