INSERT INTO menu (title, eng_name, info) VALUES ('메인반찬', 'main', '한그릇 뚝딱 메인 요리');
INSERT INTO menu (title, eng_name, info) VALUES ('국물요리', 'soup', '김이 모락모락 국.찌개');
INSERT INTO menu (title, eng_name, info) VALUES ('밑반찬', 'side', '언제 먹어도 든든한 밑반찬');
INSERT INTO best_category (title) VALUES ('할인특가세트상품');
INSERT INTO best_category (title) VALUES ('풍성한고기반찬');
INSERT INTO best_category (title) VALUES ('편리한반찬세트');
INSERT INTO best_category (title) VALUES ('간편한 덮밥요리');
INSERT INTO best_category (title) VALUES ('우리아이영양반찬');

-- 재고 관련
# UPDATE detail SET availability = 78 WHERE id = 1;
# UPDATE detail SET availability = 13 WHERE id = 2;
# UPDATE detail SET availability = 45 WHERE id = 3;
# UPDATE detail SET availability = 10 WHERE id = 4;
# UPDATE detail SET availability = 21 WHERE id = 5;
# UPDATE detail SET availability = 1 WHERE id = 6;
# UPDATE detail SET availability = 2 WHERE id = 7;
# UPDATE detail SET availability = 2 WHERE id = 8;
# UPDATE detail SET availability = 23 WHERE id = 9;
# UPDATE detail SET availability = 34 WHERE id = 10;
# UPDATE detail SET availability = 39 WHERE id = 11;
# UPDATE detail SET availability = 23 WHERE id = 12;
# UPDATE detail SET availability = 0 WHERE id = 13;
# UPDATE detail SET availability = 0 WHERE id = 14;
# UPDATE detail SET availability = 0 WHERE id = 15;
# UPDATE detail SET availability = 0 WHERE id = 16;
# UPDATE detail SET availability = 0 WHERE id = 17;
# UPDATE detail SET availability = 88 WHERE id = 18;
# UPDATE detail SET availability = 76 WHERE id = 19;
# UPDATE detail SET availability = 84 WHERE id = 20;
# UPDATE detail SET availability = 83 WHERE id = 21;
# UPDATE detail SET availability = 92 WHERE id = 22;
# UPDATE detail SET availability = 80 WHERE id = 23;
# UPDATE detail SET availability = 92 WHERE id = 24;
# UPDATE detail SET availability = 49 WHERE id = 25;
# UPDATE detail SET availability = 32 WHERE id = 26;
# UPDATE detail SET availability = 13 WHERE id = 27;
